version: '3.8'

services:
  postgres:
    image: postgres:9.6.23
    networks:
      - redmine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB_USER=dbuser
      - POSTGRES_DB=redmineapp
    volumes:
      - ./docker-scripts/database:/docker-entrypoint-initdb.d/
      - ./db:/def-data-script/
    ports:
      - 5432:5432

  redmineA:
    image: redmine:4.2.2
    networks:
      - redmine
    ports:
      - 3000:3000
    environment:
      - REDMINE_DB_POSTGRES=postgres
      - REDMINE_DB_DATABASE=redmineapp1
      - REDMINE_DB_PASSWORD=docker

  redmineB:
    image: redmine:4.2.2
    networks:
      - redmine
    ports:
      - 3010:3000
    environment:
      - REDMINE_DB_POSTGRES=postgres
      - REDMINE_DB_DATABASE=redmineapp2
      - REDMINE_DB_PASSWORD=docker

  redmineApp:
    build:
      context: .
      dockerfile: docker-scripts/app/Dockerfile
    image: "redmineapp"
    networks:
      - redmine
    ports:
      - 8080:8080
    environment:
      - REDMINE_A_URL=redminea:3000
      - REDMINE_B_URL=redmineb:3000
      - POSTGRES_URL=postgres:5432

networks:
  redmine:
    driver: bridge